// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ccms.proto

package configpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_4282842ec299a6a4, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Output struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_4282842ec299a6a4, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Input)(nil), "configpb.Input")
	proto.RegisterType((*Output)(nil), "configpb.Output")
}

func init() { proto.RegisterFile("ccms.proto", fileDescriptor_4282842ec299a6a4) }

var fileDescriptor_4282842ec299a6a4 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0xce, 0x2d,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x2f, 0x48,
	0x52, 0x92, 0xe4, 0x62, 0xf5, 0xcc, 0x2b, 0x28, 0x2d, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0xe4, 0xb8, 0xd8, 0xfc, 0x4b, 0x4b,
	0x40, 0x72, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x50, 0x59, 0x08, 0xc7, 0xc8, 0x88,
	0x8b, 0xc5, 0xd9, 0xd9, 0x37, 0x58, 0x48, 0x8b, 0x8b, 0xd9, 0x3d, 0xb5, 0x44, 0x88, 0x5f, 0x0f,
	0x66, 0xa8, 0x1e, 0xd8, 0x44, 0x29, 0x01, 0x84, 0x00, 0xc4, 0x1c, 0x25, 0x06, 0x27, 0xfe, 0x55,
	0x4c, 0x3c, 0x49, 0xb9, 0xc5, 0x70, 0x99, 0x24, 0x36, 0xb0, 0x83, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0x6b, 0xc2, 0xee, 0x9e, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CCMSClient is the client API for CCMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CCMSClient interface {
	Get(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type cCMSClient struct {
	cc *grpc.ClientConn
}

func NewCCMSClient(cc *grpc.ClientConn) CCMSClient {
	return &cCMSClient{cc}
}

func (c *cCMSClient) Get(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/configpb.CCMS/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CCMSServer is the server API for CCMS service.
type CCMSServer interface {
	Get(context.Context, *Input) (*Output, error)
}

// UnimplementedCCMSServer can be embedded to have forward compatible implementations.
type UnimplementedCCMSServer struct {
}

func (*UnimplementedCCMSServer) Get(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterCCMSServer(s *grpc.Server, srv CCMSServer) {
	s.RegisterService(&_CCMS_serviceDesc, srv)
}

func _CCMS_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCMSServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configpb.CCMS/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCMSServer).Get(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _CCMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "configpb.CCMS",
	HandlerType: (*CCMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CCMS_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccms.proto",
}
