// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs2/cs2.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Input CommRequest
type CommRequest struct {
	Value []*Input `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	// User / App access token that need to be verified
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommRequest) Reset()         { *m = CommRequest{} }
func (m *CommRequest) String() string { return proto.CompactTextString(m) }
func (*CommRequest) ProtoMessage()    {}
func (*CommRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{0}
}

func (m *CommRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommRequest.Unmarshal(m, b)
}
func (m *CommRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommRequest.Marshal(b, m, deterministic)
}
func (m *CommRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommRequest.Merge(m, src)
}
func (m *CommRequest) XXX_Size() int {
	return xxx_messageInfo_CommRequest.Size(m)
}
func (m *CommRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommRequest proto.InternalMessageInfo

func (m *CommRequest) GetValue() []*Input {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CommRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type Input struct {
	//Unique TemplateID
	TemplateId string `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	//could be XML/JSON/other
	Data *_struct.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	//Additional details
	Meta                 *Attributes `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{1}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *Input) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Input) GetMeta() *Attributes {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Attributes struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Additionaltext       string   `protobuf:"bytes,2,opt,name=additionaltext,proto3" json:"additionaltext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{2}
}

func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (m *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(m, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Attributes) GetAdditionaltext() string {
	if m != nil {
		return m.Additionaltext
	}
	return ""
}

type CommResponse struct {
	TemplateBody         []*Details `protobuf:"bytes,1,rep,name=templateBody,proto3" json:"templateBody,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommResponse) Reset()         { *m = CommResponse{} }
func (m *CommResponse) String() string { return proto.CompactTextString(m) }
func (*CommResponse) ProtoMessage()    {}
func (*CommResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{3}
}

func (m *CommResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommResponse.Unmarshal(m, b)
}
func (m *CommResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommResponse.Marshal(b, m, deterministic)
}
func (m *CommResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommResponse.Merge(m, src)
}
func (m *CommResponse) XXX_Size() int {
	return xxx_messageInfo_CommResponse.Size(m)
}
func (m *CommResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommResponse proto.InternalMessageInfo

func (m *CommResponse) GetTemplateBody() []*Details {
	if m != nil {
		return m.TemplateBody
	}
	return nil
}

func (m *CommResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Details struct {
	Medium               string   `protobuf:"bytes,1,opt,name=medium,proto3" json:"medium,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Placeholders         []string `protobuf:"bytes,4,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{4}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Details) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Details) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Details) GetPlaceholders() []string {
	if m != nil {
		return m.Placeholders
	}
	return nil
}

// Error error response as per the standard specification.
type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea666de28fdd7f20, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*CommRequest)(nil), "bms.cs.v1.CommRequest")
	proto.RegisterType((*Input)(nil), "bms.cs.v1.Input")
	proto.RegisterType((*Attributes)(nil), "bms.cs.v1.Attributes")
	proto.RegisterType((*CommResponse)(nil), "bms.cs.v1.CommResponse")
	proto.RegisterType((*Details)(nil), "bms.cs.v1.Details")
	proto.RegisterType((*Error)(nil), "bms.cs.v1.Error")
}

func init() { proto.RegisterFile("cs2/cs2.proto", fileDescriptor_ea666de28fdd7f20) }

var fileDescriptor_ea666de28fdd7f20 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x51, 0x8b, 0x13, 0x31,
	0x10, 0xb6, 0xd7, 0xf6, 0x8e, 0x4e, 0x5b, 0x91, 0x80, 0xd7, 0xe5, 0x10, 0x29, 0xfb, 0x70, 0x54,
	0x84, 0x2d, 0xb7, 0x82, 0x6f, 0x3e, 0x58, 0x15, 0xb9, 0x17, 0x91, 0x3d, 0x41, 0xf0, 0x2d, 0x9b,
	0x8c, 0xe7, 0xea, 0xee, 0x66, 0xcd, 0x4c, 0x8a, 0x3e, 0xf9, 0x7f, 0xfc, 0x95, 0x92, 0xec, 0xd6,
	0x4b, 0xf5, 0x2d, 0xf9, 0xe6, 0xcb, 0xe4, 0xfb, 0xbe, 0x19, 0x58, 0x2a, 0xca, 0xb7, 0x8a, 0xf2,
	0xac, 0xb3, 0x86, 0x8d, 0x98, 0x95, 0x0d, 0x65, 0x8a, 0xb2, 0xfd, 0xd5, 0xc5, 0xa3, 0x5b, 0x63,
	0x6e, 0x6b, 0xdc, 0x86, 0x42, 0xe9, 0x3e, 0x6f, 0x89, 0xad, 0x53, 0xdc, 0x13, 0xd3, 0x8f, 0x30,
	0x7f, 0x65, 0x9a, 0xa6, 0xc0, 0xef, 0x0e, 0x89, 0xc5, 0x25, 0x4c, 0xf7, 0xb2, 0x76, 0x98, 0x8c,
	0xd6, 0xe3, 0xcd, 0x3c, 0x7f, 0x90, 0xfd, 0xed, 0x93, 0x5d, 0xb7, 0x9d, 0xe3, 0xa2, 0x2f, 0x8b,
	0x35, 0xcc, 0xa5, 0x52, 0x48, 0xf4, 0xc1, 0x7c, 0xc3, 0x36, 0x39, 0x59, 0x8f, 0x36, 0xb3, 0x22,
	0x86, 0xd2, 0x5f, 0x30, 0x0d, 0x2f, 0xc4, 0x63, 0x00, 0xc6, 0xa6, 0xab, 0x25, 0xe3, 0xb5, 0x4e,
	0x46, 0x81, 0x19, 0x21, 0xe2, 0x29, 0x4c, 0xb4, 0x64, 0x19, 0x7a, 0xcc, 0xf3, 0x55, 0xd6, 0xcb,
	0xcd, 0x0e, 0x72, 0xb3, 0x9b, 0x20, 0xb7, 0x08, 0x24, 0xf1, 0x04, 0x26, 0x0d, 0xb2, 0x4c, 0xc6,
	0x81, 0xfc, 0x30, 0x92, 0xf7, 0x92, 0xd9, 0x56, 0xa5, 0x63, 0xa4, 0x22, 0x50, 0xd2, 0x77, 0x00,
	0x77, 0x98, 0x48, 0xe0, 0x8c, 0x5c, 0xf9, 0x15, 0x15, 0x0f, 0x12, 0x0e, 0x57, 0x71, 0x09, 0xf7,
	0xa5, 0xd6, 0x15, 0x57, 0xa6, 0x95, 0x35, 0xe3, 0x0f, 0x1e, 0xdc, 0xfc, 0x83, 0xa6, 0x2d, 0x2c,
	0xfa, 0xa4, 0xa8, 0x33, 0x2d, 0xa1, 0x78, 0x0e, 0x8b, 0x83, 0x8b, 0x9d, 0xd1, 0x3f, 0x87, 0xc4,
	0x44, 0x24, 0xe9, 0x35, 0xb2, 0xac, 0x6a, 0x2a, 0x8e, 0x78, 0x3e, 0x62, 0xb4, 0xd6, 0xd8, 0xc1,
	0x70, 0x1c, 0xf1, 0x1b, 0x8f, 0x17, 0x7d, 0x39, 0x25, 0x38, 0x1b, 0x1a, 0x88, 0x73, 0x38, 0x6d,
	0x50, 0x57, 0xae, 0x19, 0xb4, 0x0f, 0x37, 0x21, 0x60, 0x52, 0xfa, 0xaf, 0x7b, 0xc1, 0xe1, 0x1c,
	0x1b, 0x1d, 0x1f, 0x1b, 0x4d, 0x61, 0xd1, 0xd5, 0x52, 0xe1, 0x17, 0x53, 0x6b, 0xb4, 0x94, 0x4c,
	0xd6, 0xe3, 0xcd, 0xac, 0x38, 0xc2, 0xd2, 0x17, 0x30, 0x0d, 0x22, 0x7c, 0x6b, 0x65, 0x34, 0x0e,
	0x1f, 0x86, 0xb3, 0x1f, 0xba, 0x46, 0x52, 0xb6, 0xea, 0x7c, 0x2c, 0x87, 0xa1, 0x47, 0x50, 0x7e,
	0x03, 0x4b, 0x9f, 0x91, 0x6b, 0x2b, 0x25, 0x3d, 0x20, 0x76, 0xb0, 0x7c, 0x8b, 0xfc, 0x5e, 0x5a,
	0x42, 0x1d, 0xdc, 0x9f, 0x47, 0x76, 0xa3, 0xc5, 0xbb, 0x58, 0xfd, 0x87, 0xf7, 0x31, 0xa7, 0xf7,
	0x76, 0xab, 0x4f, 0x7e, 0x9b, 0xb7, 0x8a, 0xb6, 0xfb, 0xab, 0xdf, 0x27, 0x77, 0x9b, 0x5d, 0x9e,
	0x86, 0x1d, 0x79, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x37, 0x4d, 0x58, 0x0d, 0xfc, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationClient interface {
	//GetParsedBody will give the parsed body for templatedID sent
	GetParsedBody(ctx context.Context, in *CommRequest, opts ...grpc.CallOption) (*CommResponse, error)
}

type communicationClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationClient(cc *grpc.ClientConn) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) GetParsedBody(ctx context.Context, in *CommRequest, opts ...grpc.CallOption) (*CommResponse, error) {
	out := new(CommResponse)
	err := c.cc.Invoke(ctx, "/bms.cs.v1.Communication/GetParsedBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
type CommunicationServer interface {
	//GetParsedBody will give the parsed body for templatedID sent
	GetParsedBody(context.Context, *CommRequest) (*CommResponse, error)
}

// UnimplementedCommunicationServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationServer struct {
}

func (*UnimplementedCommunicationServer) GetParsedBody(ctx context.Context, req *CommRequest) (*CommResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParsedBody not implemented")
}

func RegisterCommunicationServer(s *grpc.Server, srv CommunicationServer) {
	s.RegisterService(&_Communication_serviceDesc, srv)
}

func _Communication_GetParsedBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetParsedBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bms.cs.v1.Communication/GetParsedBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetParsedBody(ctx, req.(*CommRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Communication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bms.cs.v1.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParsedBody",
			Handler:    _Communication_GetParsedBody_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs2/cs2.proto",
}
